# Generated by Django 5.2.6 on 2025-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_time',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date_lunar',
            field=models.DateField(blank=True, help_text='음력 생년월일', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date_solar',
            field=models.DateField(blank=True, help_text='양력 생년월일', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_time_units',
            field=models.CharField(blank=True, choices=[('자시', '자시'), ('축시', '축시'), ('인시', '인시'), ('묘시', '묘시'), ('진시', '진시'), ('사시', '사시'), ('오시', '오시'), ('미시', '미시'), ('신시', '신시'), ('유시', '유시'), ('술시', '술시'), ('해시', '해시'), ('모름', '모름')], help_text='시진', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_ganji',
            field=models.CharField(blank=True, help_text='일주', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_ganji',
            field=models.CharField(blank=True, help_text='시주', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_ganji',
            field=models.CharField(blank=True, help_text='월주', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='solar_or_lunar',
            field=models.CharField(blank=True, choices=[('solar', '양력'), ('lunar', '음력')], help_text='사용자가 입력한 생년월일 타입', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='yearly_ganji',
            field=models.CharField(blank=True, help_text='년주', max_length=2, null=True),
        ),
    ]
