# Generated by Django 5.2.6 on 2025-10-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_add_saju_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_time_units",
            field=models.CharField(
                blank=True,
                choices=[
                    ("자시", "자시"),
                    ("축시", "축시"),
                    ("인시", "인시"),
                    ("묘시", "묘시"),
                    ("진시", "진시"),
                    ("사시", "사시"),
                    ("오시", "오시"),
                    ("미시", "미시"),
                    ("신시", "신시"),
                    ("유시", "유시"),
                    ("술시", "술시"),
                    ("해시", "해시"),
                    ("야자시", "야자시"),
                ],
                help_text="시진",
                max_length=10,
                null=True,
            ),
        ),
    ]
