# Generated by Django 5.2.6 on 2025-10-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_birth_time_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='탈퇴 시간 (soft delete)', null=True),
        ),
    ]
