# Generated by Django 5.2.6 on 2025-10-01 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChakraImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="chakras/%Y/%m/%d/")),
                ("chakra_type", models.CharField(default="default", max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "device_make",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "device_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_chakra_user_id_946bb7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FortuneResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("for_date", models.DateField()),
                ("gapja_code", models.IntegerField()),
                ("gapja_name", models.CharField(max_length=10)),
                ("gapja_element", models.CharField(max_length=5)),
                ("fortune_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-for_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "for_date"],
                        name="core_fortun_user_id_7095f7_idx",
                    )
                ],
                "unique_together": {("user", "for_date")},
            },
        ),
    ]
