# Generated by Django 5.2.6 on 2025-10-01 16:49

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chakraimage",
            name="date",
            field=models.DateField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="chakraimage",
            index=models.Index(
                fields=["user", "date"], name="core_chakra_user_id_9791aa_idx"
            ),
        ),
    ]
