# Generated by Django 5.2.6 on 2025-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_chakraimage_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fortuneresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="pending",
                help_text="Current status of fortune generation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fortuneresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chakraimage",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="fortuneresult",
            name="fortune_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="fortuneresult",
            name="gapja_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fortuneresult",
            name="gapja_element",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="fortuneresult",
            name="gapja_name",
            field=models.CharField(default="", max_length=10),
        ),
    ]
