# Generated by Django 5.2.6 on 2025-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fortuneresult_status_fortuneresult_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fortuneresult",
            name="fortune_score",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
