# Generated by Django 5.2.6 on 2025-10-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fortuneresult_fortune_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chakraimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chakras/%Y/%m/%d/"
            ),
        ),
    ]
