# Generated by Django 5.2.6 on 2025-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_chakraimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="fortuneresult",
            name="fortune_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="fortunes/%Y/%m/%d/"
            ),
        ),
    ]
