name: Deploy to Railway

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'fortuna_api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'fortuna_api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: server
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}
        working-directory: ./fortuna_api
